# Generated by Django 5.0.6 on 2024-06-25 08:07

from django.db import migrations, models #fichier créé pour lire le model. Chaque fois qu'on crée une class, on fait une migration


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
