# Generated by Django 5.0.6 on 2024-06-25 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='furniture',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='furniture',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='descritpion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='dimensions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furniture',
            name='colors',
            field=models.ManyToManyField(to='furniture.color'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='materials',
            field=models.ManyToManyField(to='furniture.material'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='furniture.type'),
        ),
    ]
