# Generated by Django 5.0.6 on 2024-06-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_color_material_type_rename_title_furniture_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='descritpion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='furniture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
