# Generated by Django 5.0.6 on 2024-06-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_rename_descritpion_furniture_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='type',
            new_name='type_id',
        ),
    ]
