# Generated by Django 5.0.6 on 2024-06-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_rename_type_furniture_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='type_id',
            new_name='type',
        ),
    ]
