# Generated by Django 5.0.6 on 2024-06-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0005_rename_type_id_furniture_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='image',
        ),
        migrations.AddField(
            model_name='furniture',
            name='image1',
            field=models.ImageField(default='images/vase_ocean2.jpg', upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='colors',
            field=models.ManyToManyField(blank=True, to='furniture.color'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='materials',
            field=models.ManyToManyField(blank=True, to='furniture.material'),
        ),
    ]
