# Generated by Django 5.0.6 on 2024-07-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0006_remove_furniture_image_furniture_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='image1',
            field=models.ImageField(default='images/vase_ocean2.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
