# Generated by Django 5.0.6 on 2024-07-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postal_adress',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
